### ISSUE TITLE
Request for additional parameters for replicationQueue 

### ISSUE THREAD

**Issue by nwageler** [bseltz-cohesity/scripts#135]
In times where we have a heavy replication backlog we may need to cancel more than just outdated replication tasks, but not the entire queue.  Adding some more parameters may help save some steps preventing us from needing to cancel the entire queue and then using ReplicateOldSnapshots to requeue the tasks we wanted to keep.

Would it be possible to add parameters similar to the ArchiveOldSnapshots and ReplicateOldSnapshots:

-ifExpiringAfter
-olderThan
-newerThan

Also would it be possible to add a preview (test) mode similar to "-archive" and "-replicate" parameters in ArchiveOldSnapshots and ReplicateOldSnapshots?

Thanks!!

**Comment by bseltz-cohesity** [comment]
OK I have added the following parameters:

* -olderThan: (optional) only show/cancel replications older than X days (use with -cancelall)
* -newerThan: (optional) only show/cancel replications newer than X days (use with -cancelall)
* -ifExpiringBefore: (optional) consider outdated any replicas that will expire in X days or less (use with -canceloutdated)
* -commit: (optional) perform cancelations, otherwise run in test mode
