### ISSUE TITLE
Destroy & Clone is not working properly

### ISSUE THREAD

**Issue by 101siva** [bseltz-cohesity/scripts#178]
we have created SQL Jobs to perform Destroy & clone DB's from past 10 days job showing successfully but clones is not working well.
Please help us to address this issue. 

we have 10 Clone jobs in the servers, we are facing issue only one job. we don't see any errors. 

below Code we are using to perform operation

https://github.com/bseltz-cohesity/scripts/blob/master/sql/powershell/destroyClone/README.md

https://github.com/bseltz-cohesity/scripts/tree/master/sql/powershell/cloneSQL

below code we are using to perform the DB destroy & clone 

E:\DBA\_Cohesity\Cohesity_API\destroyClone.ps1 `
      -vip coh-***** `
      -username ****** `
      -domain **** `
      -cloneType sql `
      -dbServer *** `
      -dbName *** `
      -useApiKey `
      -wait

 E:\DBA\_Cohesity\Cohesity_API\cloneSQL.ps1 `
      -vip coh-*** `
      -username ***  `
      -domain *** `
      -sourceServer ***  `
      -sourceDB *** `
      -targetServer *** `
      -targetDB ***  `
      -useApiKey `
      -latest `
      -wait

**Comment by bseltz-cohesity** [comment]
A couple of things::

1. Most often the problem is the command you put in the SQL job step may have an accidental carriage return, or incorrect line continuation characters, causing the command to be truncated when run. This is hard to spot in the SQL job editor. Copy the command out to notepad and make sure the command is all on one line and otherwise correct, then paste it back into the SQL job editor. You can test that the command works as expected by pasting it into a PowerShell window.
2. I have made a small update the the cloneSQL.ps1 script to ensure that it returns a non-zero exit code for all unsuccessful outcomes, please get the updated script here: https://github.com/cohesity/community-automation-samples/tree/main/sql/powershell/cloneSQL
