### ISSUE TITLE
Bugs in oracleDBs.py

### ISSUE THREAD

**Issue by nadigpradyumna** [bseltz-cohesity/scripts#188]
1. In the `for db in servername['applicationNodes']:` line, servername is a string (the server's name), not a dictionary. Therefore, you cannot access ['applicationNodes'] on it. 
2. The script assumes sources[0]['nodes'] always exists. However, sources may not have valid data if no Oracle databases are found.
3. The fraSize conversion assumes it is always an integer. If this field is absent, the script may crash.

**Comment by bseltz-cohesity** [comment]
1. The line actually reads `for db in server['applicationNodes']:` so I'm not sure if we are looking at the same script?
2. I've reviewed the script and made a minor change in reference to your second comment.
3. again I think we're looking at different scripts because the script handle missing properties correctly.
The script is here: https://github.com/cohesity/community-automation-samples/tree/main/oracle/python/oracleDBs
